require conf/distro/include/tb-distro-common.conf

DISTRO = "tb-compat-checker"

# EFI-only image with just GRUB on the ESP
WKS_FILES = "trenchboot-image-compatchecker.wks.in"

# No extra boot files on ESP (no skl.bin, no ACMs)
IMAGE_EFI_BOOT_FILES = ""

# No initramfs needed
INITRAMFS_IMAGE = ""
INITRAMFS_IMAGE_BUNDLE = "0"
